"""Initial migration

Revision ID: 78acc673121c
Revises: 
Create Date: 2026-01-22 15:37:27.402870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78acc673121c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('capacidad', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('caracteristicas', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('SUPER_ADMIN', 'ADMIN', 'EMPLEADO', 'CLIENTE', name='rolenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('alertas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('VACUNA', 'HERRAJE', 'DESPARASITACION', 'PAGO', 'EVENTO', 'CUMPLEAÑOS', 'CONTRATO', 'STOCK', 'TAREA', 'OTRO', name='tipoalertaenum'), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='prioridadalertaenum'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('mensaje', sa.String(length=1000), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_evento', sa.Date(), nullable=True),
    sa.Column('entidad_relacionada_tipo', sa.String(length=50), nullable=True),
    sa.Column('entidad_relacionada_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('tipo_cliente', sa.Enum('SOCIO_PLENO', 'PENSIONISTA', 'ALUMNO', name='tipoclienteenum'), nullable=False),
    sa.Column('estado_cuenta', sa.Enum('AL_DIA', 'DEBE', 'MOROSO', name='estadocuentaenum'), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.String(length=1000), nullable=True),
    sa.Column('contacto_emergencia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('configuracion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('empleados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('funcion', sa.Enum('VETERINARIO', 'INSTRUCTOR', 'CUIDADOR', 'ADMINISTRATIVO', 'MANTENIMIENTO', name='funcionempleadoenum'), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('foto_perfil', sa.String(length=500), nullable=True),
    sa.Column('contacto_emergencia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('caballos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('MACHO', 'HEMBRA', 'CASTRADO', name='sexocaballoenum'), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('altura', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('peso', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('propietario_id', sa.UUID(), nullable=True),
    sa.Column('box_asignado', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'RETIRADO', 'EN_TRATAMIENTO', 'FALLECIDO', name='estadocaballoenum'), nullable=False),
    sa.Column('caracteristicas', sa.String(length=1000), nullable=True),
    sa.Column('foto_principal', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['propietario_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('CLASE_GRUPAL', 'CLASE_PRIVADA', 'COMPETENCIA', 'SALIDA', 'EVENTO_SOCIAL', 'OTRO', name='tipoeventoenum'), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PROGRAMADO', 'EN_CURSO', 'FINALIZADO', 'CANCELADO', name='estadoeventoenum'), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('es_recurrente', sa.Boolean(), nullable=False),
    sa.Column('recurrencia_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['empleados.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('PENSION', 'CLASE', 'EVENTO', 'SERVICIO_EXTRA', 'OTRO', name='tipopagoenum'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA', 'TARJETA', 'CHEQUE', name='metodopagoenum'), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADO', 'VENCIDO', 'CANCELADO', name='estadopagoenum'), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('recibo_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_caballo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caballo_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_medico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caballo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('VACUNA', 'DESPARASITACION', 'TRATAMIENTO', 'CIRUGIA', 'REVISION', 'HERRAJE', 'OTRO', name='tipohistorialenum'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('veterinario', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('medicamento', sa.String(length=255), nullable=True),
    sa.Column('dosis', sa.String(length=100), nullable=True),
    sa.Column('proxima_aplicacion', sa.Date(), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('documentos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones_evento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('caballo_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Enum('CONFIRMADO', 'EN_ESPERA', 'CANCELADO', name='estadoinscripcionenum'), nullable=False),
    sa.Column('asistio', sa.Boolean(), nullable=True),
    sa.Column('comentarios', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_alimentacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caballo_id', sa.UUID(), nullable=False),
    sa.Column('tipo_alimento', sa.String(length=255), nullable=True),
    sa.Column('cantidad_diaria', sa.String(length=100), nullable=True),
    sa.Column('horarios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suplementos', sa.String(length=500), nullable=True),
    sa.Column('restricciones', sa.String(length=500), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caballo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_alimentacion')
    op.drop_table('inscripciones_evento')
    op.drop_table('historial_medico')
    op.drop_table('fotos_caballo')
    op.drop_table('pagos')
    op.drop_table('eventos')
    op.drop_table('caballos')
    op.drop_table('empleados')
    op.drop_table('configuracion')
    op.drop_table('clientes')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('boxes')
    # ### end Alembic commands ###
