"""add_egreso_model

Revision ID: 90ba6f7b2ad4
Revises: 0094eb130e07
Create Date: 2026-02-06 13:55:59.333587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ba6f7b2ad4'
down_revision = '0094eb130e07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egresos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('ALIMENTACION', 'VETERINARIO', 'HERRERO', 'MANTENIMIENTO', 'SERVICIOS', 'SALARIOS', 'SUMINISTROS', 'EQUIPAMIENTO', 'OTRO', name='tipoegresoenum'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_egreso', sa.Date(), nullable=False),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('comprobante_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('egresos')
    # ### end Alembic commands ###
