"""expand caballo model with complete medical and management data

Revision ID: ada89328ced7
Revises: c81481935e3e
Create Date: 2026-01-26 12:25:11.993215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ada89328ced7'
down_revision = 'c81481935e3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create manejoenum if it doesn't exist
    from sqlalchemy import text
    conn = op.get_bind()

    # Check if enum exists, if not create it
    result = conn.execute(text(
        "SELECT 1 FROM pg_type WHERE typname = 'manejoenum'"
    )).scalar()

    if not result:
        conn.execute(text(
            "CREATE TYPE manejoenum AS ENUM ('BOX', 'BOX_PIQUETE', 'PIQUETE', 'PALENQUE', 'CROSS_TIE')"
        ))

    op.create_table('antiparasitarios_registros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caballo_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('marca', sa.String(length=200), nullable=True),
    sa.Column('drogas', sa.String(length=500), nullable=True),
    sa.Column('dosis', sa.String(length=100), nullable=True),
    sa.Column('proxima_aplicacion', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudios_medicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caballo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('veterinario', sa.String(length=200), nullable=True),
    sa.Column('zona_estudiada', sa.String(length=200), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('archivo_url', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('herrajes_registros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caballo_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('herrador', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('proximo_herraje', sa.Date(), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revisiones_dentales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caballo_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('veterinario', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('proxima_revision', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacunas_registros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caballo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('veterinario', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=200), nullable=True),
    sa.Column('frecuencia_dias', sa.Integer(), nullable=True),
    sa.Column('proxima_fecha', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('aplicada', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('caballos', sa.Column('numero_chip', sa.String(length=50), nullable=False))
    op.add_column('caballos', sa.Column('id_fomento', sa.String(length=50), nullable=True))
    op.add_column('caballos', sa.Column('pedigree', sa.Text(), nullable=True))
    op.add_column('caballos', sa.Column('qr_code', sa.String(length=500), nullable=True))
    op.add_column('caballos', sa.Column('grano_balanceado', sa.String(length=200), nullable=True))
    op.add_column('caballos', sa.Column('suplementos', sa.String(length=500), nullable=True))
    op.add_column('caballos', sa.Column('cantidad_comidas_dia', sa.Integer(), nullable=True))
    op.add_column('caballos', sa.Column('detalles_alimentacion', sa.Text(), nullable=True))
    op.add_column('caballos', sa.Column('tipo_manejo', sa.Enum('BOX', 'BOX_PIQUETE', 'PIQUETE', 'PALENQUE', 'CROSS_TIE', name='manejoenum'), nullable=True))
    op.add_column('caballos', sa.Column('dias_trabajo', sa.String(length=100), nullable=True))
    op.add_column('caballos', sa.Column('dias_descanso', sa.String(length=100), nullable=True))
    op.add_column('caballos', sa.Column('jinete_asignado', sa.String(length=100), nullable=True))
    op.add_column('caballos', sa.Column('tiempo_trabajo_diario', sa.Integer(), nullable=True))
    op.add_column('caballos', sa.Column('trabajo_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('caballos', sa.Column('embocadura_1', sa.String(length=200), nullable=True))
    op.add_column('caballos', sa.Column('embocadura_2', sa.String(length=200), nullable=True))
    op.add_column('caballos', sa.Column('cuidados_especiales', sa.Text(), nullable=True))
    op.add_column('caballos', sa.Column('otra_info_1', sa.Text(), nullable=True))
    op.add_column('caballos', sa.Column('otra_info_2', sa.Text(), nullable=True))
    op.alter_column('caballos', 'caracteristicas',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_caballos_id_fomento'), 'caballos', ['id_fomento'], unique=True)
    op.create_index(op.f('ix_caballos_nombre'), 'caballos', ['nombre'], unique=False)
    op.create_index(op.f('ix_caballos_numero_chip'), 'caballos', ['numero_chip'], unique=True)
    op.add_column('fotos_caballo', sa.Column('es_principal', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fotos_caballo', 'es_principal')
    op.drop_index(op.f('ix_caballos_numero_chip'), table_name='caballos')
    op.drop_index(op.f('ix_caballos_nombre'), table_name='caballos')
    op.drop_index(op.f('ix_caballos_id_fomento'), table_name='caballos')
    op.alter_column('caballos', 'caracteristicas',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('caballos', 'otra_info_2')
    op.drop_column('caballos', 'otra_info_1')
    op.drop_column('caballos', 'cuidados_especiales')
    op.drop_column('caballos', 'embocadura_2')
    op.drop_column('caballos', 'embocadura_1')
    op.drop_column('caballos', 'trabajo_config')
    op.drop_column('caballos', 'tiempo_trabajo_diario')
    op.drop_column('caballos', 'jinete_asignado')
    op.drop_column('caballos', 'dias_descanso')
    op.drop_column('caballos', 'dias_trabajo')
    op.drop_column('caballos', 'tipo_manejo')
    op.drop_column('caballos', 'detalles_alimentacion')
    op.drop_column('caballos', 'cantidad_comidas_dia')
    op.drop_column('caballos', 'suplementos')
    op.drop_column('caballos', 'grano_balanceado')
    op.drop_column('caballos', 'qr_code')
    op.drop_column('caballos', 'pedigree')
    op.drop_column('caballos', 'id_fomento')
    op.drop_column('caballos', 'numero_chip')
    op.drop_table('vacunas_registros')
    op.drop_table('revisiones_dentales')
    op.drop_table('herrajes_registros')
    op.drop_table('estudios_medicos')
    op.drop_table('antiparasitarios_registros')
    # ### end Alembic commands ###
