"""add permisos to usuarios and expand alertas system

Revision ID: c81481935e3e
Revises: 78acc673121c
Create Date: 2026-01-25 22:13:32.419271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c81481935e3e'
down_revision = '78acc673121c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create frecuenciaalertaenum if it doesn't exist and add new values to tipoalertaenum
    from sqlalchemy import text
    conn = op.get_bind()

    # Check if enum exists, if not create it
    result = conn.execute(text(
        "SELECT 1 FROM pg_type WHERE typname = 'frecuenciaalertaenum'"
    )).scalar()

    if not result:
        conn.execute(text(
            "CREATE TYPE frecuenciaalertaenum AS ENUM ('UNICA', 'DIARIA', 'SEMANAL', 'MENSUAL', 'CADA_X_DIAS')"
        ))

    # Add new values to tipoalertaenum enum if they don't exist
    conn.execute(text(
        "DO $$ BEGIN "
        "IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'MANTENIMIENTO' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'tipoalertaenum')) THEN "
        "ALTER TYPE tipoalertaenum ADD VALUE 'MANTENIMIENTO'; "
        "END IF; END $$;"
    ))
    conn.execute(text(
        "DO $$ BEGIN "
        "IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'VETERINARIA' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'tipoalertaenum')) THEN "
        "ALTER TYPE tipoalertaenum ADD VALUE 'VETERINARIA'; "
        "END IF; END $$;"
    ))

    # Use existing enum types
    tipoalertaenum = postgresql.ENUM('VACUNA', 'HERRAJE', 'DESPARASITACION', 'PAGO', 'EVENTO', 'CUMPLEAÑOS', 'CONTRATO', 'STOCK', 'TAREA', 'MANTENIMIENTO', 'VETERINARIA', 'OTRO', name='tipoalertaenum', create_type=False)
    prioridadalertaenum = postgresql.ENUM('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='prioridadalertaenum', create_type=False)
    frecuenciaalertaenum = postgresql.ENUM('UNICA', 'DIARIA', 'SEMANAL', 'MENSUAL', 'CADA_X_DIAS', name='frecuenciaalertaenum', create_type=False)

    op.create_table('tipos_alerta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', tipoalertaenum, nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('prioridad_default', prioridadalertaenum, nullable=False),
    sa.Column('frecuencia', frecuenciaalertaenum, nullable=False),
    sa.Column('dias_anticipacion', sa.Integer(), nullable=True),
    sa.Column('intervalo_dias', sa.Integer(), nullable=True),
    sa.Column('hora_envio', sa.String(length=5), nullable=True),
    sa.Column('enviar_a_roles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('enviar_a_usuarios', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('enviar_a_responsables', sa.Boolean(), nullable=False),
    sa.Column('canal_sistema', sa.Boolean(), nullable=False),
    sa.Column('canal_email', sa.Boolean(), nullable=False),
    sa.Column('canal_push', sa.Boolean(), nullable=False),
    sa.Column('plantilla_titulo', sa.String(length=500), nullable=True),
    sa.Column('plantilla_mensaje', sa.Text(), nullable=True),
    sa.Column('condiciones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion_alertas_usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('alertas_sistema', sa.Boolean(), nullable=False),
    sa.Column('alertas_email', sa.Boolean(), nullable=False),
    sa.Column('alertas_push', sa.Boolean(), nullable=False),
    sa.Column('tipos_alertas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('horario_inicio', sa.String(length=5), nullable=True),
    sa.Column('horario_fin', sa.String(length=5), nullable=True),
    sa.Column('dias_semana', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('agrupar_alertas', sa.Boolean(), nullable=False),
    sa.Column('intervalo_agrupacion', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.add_column('alertas', sa.Column('tipo_alerta_id', sa.UUID(), nullable=True))
    op.add_column('alertas', sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True))
    op.add_column('alertas', sa.Column('acciones_disponibles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('alertas', sa.Column('datos_adicionales', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('alertas', 'mensaje',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('alertas', 'fecha_evento',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'alertas', 'tipos_alerta', ['tipo_alerta_id'], ['id'], ondelete='SET NULL')
    op.add_column('usuarios', sa.Column('permisos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'permisos')
    op.drop_constraint(None, 'alertas', type_='foreignkey')
    op.alter_column('alertas', 'fecha_evento',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('alertas', 'mensaje',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_column('alertas', 'datos_adicionales')
    op.drop_column('alertas', 'acciones_disponibles')
    op.drop_column('alertas', 'fecha_vencimiento')
    op.drop_column('alertas', 'tipo_alerta_id')
    op.drop_table('configuracion_alertas_usuario')
    op.drop_table('tipos_alerta')
    # ### end Alembic commands ###
